development:
  adapter: postgresql
  encoding: unicode
  database: dummy_development
  pool: 5
  host: localhost
  username: jack
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: dummy_test
  pool: 5
  host: localhost
  username: jack
  password: secret

production:
  adapter: postgresql
  encoding: unicode
  database: dummy_production
  pool: 5
  host: localhost
  username: jack
  password: secret
